// Code generated by goctl. DO NOT EDIT.
// Source: data.proto

package server

import (
	"context"

	"oos-system/app/rpc/data/internal/logic"
	"oos-system/app/rpc/data/internal/svc"
	"oos-system/app/rpc/data/pb"
)

type DataServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedDataServer
}

func NewDataServer(svcCtx *svc.ServiceContext) *DataServer {
	return &DataServer{
		svcCtx: svcCtx,
	}
}

func (s *DataServer) Put(ctx context.Context, in *pb.PutRequest) (*pb.PutResponse, error) {
	l := logic.NewPutLogic(ctx, s.svcCtx)
	return l.Put(in)
}

func (s *DataServer) Get(ctx context.Context, in *pb.GetRequest) (*pb.GetResponse, error) {
	l := logic.NewGetLogic(ctx, s.svcCtx)
	return l.Get(in)
}
