// Code generated by goctl. DO NOT EDIT.
package types

type GetCaptchaReq struct {
	Id string `form:"id,optional"`
}

type GetCaptchaResp struct {
	Id          string `json:"id"`
	ImgbaseCode string `json:"imgbaseCode"`
}

type RegisterReq struct {
	Username   string `json:"username"`
	Password   string `json:"password"`
	UniqueCode string `json:"uniqueCode"`
	Captcha    string `json:"captcha"`
}

type RegisterResp struct {
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	Username string `json:"username"`
}

type DelReq struct {
}

type DelResp struct {
}

type BucketInfo struct {
	Id             int64  `json:"id"`
	Username       string `json:"username"`
	BucketName     string `json:"bucketName"`
	CapacityCur    string `json:"capacityCur"`
	ObjectNum      int64  `json:"objectNum"`
	Premission     int64  `json:"premission"`
	UserPremission int64  `json:"userPremission"`
	CreateTime     string `json:"createTime"`
	UpdateTime     string `json:"updateTime"`
}

type GetAllBucketReq struct {
}

type GetBucketByBucketNameReq struct {
	BucketName string `form:"bucketName"`
}

type GetAllBucketResq struct {
	List []BucketInfo `json:"list"`
}

type CreateBucketReq struct {
	BucketName string `json:"bucketName"`
	Version    bool   `json:"version"`
	Permission int64  `json:"permission"` //桶权限 0 公共 | 1 私有
}

type CreateBucketResq struct {
}

type ObjectInfo struct {
	Name       string `json:"name"`
	ObjectName string `json:"objectName"`
	CreateTime string `json:"createTime"`
	Size       int64  `json:"size"`
	IsDir      bool   `json:"isDir"`
	HashCode   string `json:"hashCode"`
}

type FilePathReq struct {
	BucketName string `form:"bucketName"`
	Path       string `form:"path"`
}

type FilePathResp struct {
	BucketPathList []ObjectInfo `json:"bucketPathList"`
}

type DeleteFileReq struct {
	BucketName string `json:"bucketName"`
	Path       string `json:"path"`
	IsDir      bool   `json:"isDir"`
	HashCode   string `json:"hashCode"`
	Size       int64  `json:"size"`
}

type DeleteFileResp struct {
}

type CreateFileFolderReq struct {
	BucketName     string `json:"bucketName"`
	FileFloderPath string `json:"fileFloderPath"`
}

type CreateFileFolderResp struct {
}

type AddPolicyReq struct {
	BucketName     string `json:"bucketName"`
	UserName       string `json:"userName"`
	UserPermission string `json:"userPermission"`
}

type AddPolicyResp struct {
}

type PolicyInfo struct {
	UserName       string `json:"userName"`
	BucketName     string `json:"bucketName"`
	UserPermission string `json:"userPermission"`
}

type GetAllPolicyReq struct {
	BucketName string `form:"bucketName"`
}

type GetAllPolicyResp struct {
	List []PolicyInfo `json:"list"`
}

type UpdatePolicyReq struct {
	UserName      string `json:"userName"`
	BucketName    string `json:"bucketName"`
	OldPermission string `json:"oldPermission"`
	NewPermission string `json:"newPermission"`
}

type UpdatePolicyResp struct {
}

type RemovePolicyReq struct {
	UserName       string `json:"userName"`
	BucketName     string `json:"bucketName"`
	UserPermission string `json:"userPermission"`
}

type RemovePolicyResp struct {
}

type UpdateBucketPermissionReq struct {
	BucketName string `json:"bucketName"`
	Permission string `json:"permission"`
}

type UpdateBucketPermissionResp struct {
}

type UploadChunkReq struct {
	ChunkNumber      int64  `form:"chunkNumber"`
	ChunkSize        int64  `form:"chunkSize"`
	CurrentChunkSize int64  `form:"currentChunkSize"`
	TotalSize        int64  `form:"totalSize"`
	Identifier       string `form:"identifier"`
	Filename         string `form:"filename"`
	RelativePath     string `form:"relativePath"`
	TotalChunks      int64  `form:"totalChunks"`
	BucketName       string `form:"bucketName"`
	FilePath         string `form:"filePath"`
}

type UploadChunkResp struct {
	Uploaded   []int64 `json:"uploaded"`
	Success    bool    `json:"success"`
	NeedMerge  bool    `json:"needMerge"`
	SkipUpload bool    `json:"skipUpload"`
}

type UploadChunkGetReq struct {
	ChunkNumber      int64  `form:"chunkNumber"`
	ChunkSize        int64  `form:"chunkSize"`
	CurrentChunkSize int64  `form:"currentChunkSize"`
	TotalSize        int64  `form:"totalSize"`
	Identifier       string `form:"identifier"`
	Filename         string `form:"filename"`
	RelativePath     string `form:"relativePath"`
	TotalChunks      int64  `form:"totalChunks"`
	BucketName       string `form:"bucketName"`
	FilePath         string `form:"filePath"`
}

type MergeChunkReq struct {
	HashCode   string `json:"hashCode"`
	FileName   string `json:"fileName"`
	BucketName string `json:"bucketName"`
	FilePath   string `json:"filePath"`
	ChunkSize  string `json:"chunkSize"`
	TotalSize  int64  `json:"totalSize"`
}

type MergeChuckResp struct {
	Success bool `json:"success"`
}

type UploadNoChunkReq struct {
	BucketName string `form:"hash"`
	ObjectName string `form:"hash"`
	IsDir      bool   `form:"hash"`
	CreateUser string `form:"hash"`
	CheckCode  string `form:"hash"`
	TotalSize  int64  `form:"hash"`
	Hash       string `form:"hash"`
}

type UploadNoChunkResp struct {
	Success bool `json:"success"`
}

type PreviewReq struct {
	Path string `form:"path"`
}

type DownloadReq struct {
	BucketName string `form:"bucketName"`
	Path       string `form:"path"`
	ObjectName string `form:"objectName"`
}

type DownloadUrlReq struct {
	BucketName string `json:"bucketName"`
	Path       string `json:"path"`
	ObjectName string `json:"objectName"`
}

type DownloadUrlResp struct {
	Success bool   `json:"success"`
	Url     string `json:"objectName"`
}
